# Generated by Django 5.1 on 2024-08-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_code'),
    ]

    # operations = [
    #     migrations.RunSQL("""
    #     INSERT INTO store_collection (title)
    #     VALUES ('collection-1')
    #     """,
    #     """
    #     DELETE FROM store_collection
    #     WHERE title='collection-1'
    #     """)
    # ]
