# Generated by Django 5.1 on 2024-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240827_1900'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='product',
    #         name='slug',
    #         field=models.SlugField(blank=True, default=''),
    #     ),
    # ]
